using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;

namespace momsManagement.Models
{
    public class Children
    {
        [BsonId]
        public ObjectId _id { get; set; }                // standard BSonId generated by MongoDb
        public string Id { get; set; }                          // external Id, easier to reference: 1,2,3 etc. 
        public string Name { get; set; } = string.Empty;
        public DateTime Birthday { get; set; } = DateTime.Now;
        public string Address { get; set; } = string.Empty;

        public string Parent1 { get; set; } = string.Empty;

        public string Parent2 { get; set; } = string.Empty;
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        public DateTime CreatedOn { get; set; } = DateTime.Now;
    }
}